GET http://localhost:3333/produtos

###
POST http://localhost:3333/produto

###
GET http://localhost:3333/produto/0e49d267-bd82-4376-bf3f-af5464de60ff

###
PUT http://localhost:3333/produto/43d7be62-3761-45f4-9484-2e1ed19a954f
Content-Type: 'application/json'

{      
    "nome": "Nike NOVO",
    "modelo": "Air Force 2",
    "preco": 5000
}

###
DELETE http://localhost:3333/produto/fa31277f-6a7c-4038-9c4b-277b18b53bd0